<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ur5_lego_bringup</name>
  <version>0.1.0</version>
  <description>Launch files for UR5 Lego simulation</description>
  <maintainer email="little3tar@users.noreply.github.com">little3tar</maintainer>
  <license>MIT</license>
  <depend>rclpy</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ur5_lego_gazebo</exec_depend>
  <exec_depend>ur5_lego_description</exec_depend>
  <exec_depend>ur_simulation_gz</exec_depend>
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
